name: Gerar apk
on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar dependencias
        run: |
          yarn install
      - name: Permissao do gradlew
        run: chmod +x ./android/gradlew
      - name: Criar o apk
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload do apk
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
