on: 
  workflow_dispatch

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Publish file
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-name: 'Release 1.0'
          tag-name: 'v1.0'
          asset-name: 'app-release.apk'
