on: 
  workflow_dispatch

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Publish file
      - uses: actions/download-artifact@v2
        with:
         name: app-release.apk
